# Schema for the configuration files of the ckpractice module.
ckpractice.settings:
  type: config_object
  label: 'ckpractice settings'
  mapping:
    example:
      type: string
      label: 'Example'
